version: "3.3"
services:
  api:
    build: .
    container_name: playground-api
    expose:
      - "8080"
    command: server
    restart: always

  web:
    image: nginx:stable-alpine
    container_name: playground-web
    ports:
      - "80:8080"
    links:
      - api
    env_file:
      - .env
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx:/etc/nginx/templates
    depends_on:
      - api
    restart: always
