# This is a basic workflow that is manually triggered

name: billboard

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.


jobs:
  mac-windows:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetos: [windows, darwin]
    name: billboard for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOOS: ${{ matrix.targetos }}

      - name: Compile
        run: |
          cd cmd/billboardd
          go build .
          cd ..
          cd billboardcli
          go build .

#      - uses: actions/upload-artifact@v2
#        with:
#          name: billboardcli ${{ matrix.targetos }}
#          path: cmd/billboardcli/billboardcli
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: billboardd ${{ matrix.targetos }}
#          path: cmd/billboardd/billboardd

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64, riscv64, amd64]

    name: billboard for ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        env:
          GOARCH: ${{ matrix.arch }}

      - name: Compile
        run: |
          cd cmd/billboardd
          go build .
          cd ..
          cd billboardcli
          go build .

#      - uses: actions/upload-artifact@v2
#        with:
#          name: billboardcli ${{ matrix.arch }}
#          path: cmd/billboardcli/billboardcli
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: billboardd ${{ matrix.arch }}
#          path: cmd/billboardd/billboardd
